### ISSUE TITLE
Issue with request_fonts configuration for webpages

### ISSUE THREAD

**Issue by Banzayka** [aadcg/nyxt-config#2]
Good day,

Could you pls. kindly advise what shall be written in the config file to change web pages fonts?

Many thanks in advance!

**Comment by aadcg** [comment]
The following should help.

```lisp
(defmethod ffi-buffer-make :after ((buffer nyxt/renderer/gtk:gtk-buffer))
  "Set fonts for the WebKitGTK renderer."
  (let ((settings (webkit:webkit-web-view-get-settings (nyxt/renderer/gtk:gtk-object buffer))))
    (setf (webkit:webkit-settings-serif-font-family settings) "your-serif-font"
          (webkit:webkit-settings-sans-serif-font-family settings) "your-sans-serif-font"
          (webkit:webkit-settings-monospace-font-family settings) "your-monospace-font")))
```

**Comment by Banzayka** [comment]
Thanks for advice!

Suggested wording did not help. Checked with various sites to ensure that issue persists. Can it be explained with fact that certain webpages are being rendered with own fonts? Does Nyxt support the possibility to disable fonts autoloading by webpages?

**Comment by aadcg** [comment]
> Can it be explained with fact that certain webpages are being rendered with own fonts?

Correct.



> Does Nyxt support the possibility to disable fonts autoloading by webpages?

I believe this can be achieved by injecting custom JS code on page load. See `user-script-mode`.
